### ISSUE TITLE
Writing code to test Homoskedasticity & Multicollinearity

### ISSUE THREAD

**Issue by MatthijsvanGils** [course-dprep/covid19_on_length_of_stay-team1#26]
_Deliverable_:

- [ ] testing Homoskedasticity 
- [ ] testing Multicollinearity

**Comment by MatthijsvanGils** [comment]
opened #26 to work on this issue

**Comment by MatthijsvanGils** [comment]
_Summary_

- [ ] Homodeskacity: created a residual plot to test homodeskacity. We could also choose for Breusch-pagan test 
- [ ] Multicollinearity: created code for VIF test, correlation matrix and eigenvalues and condition number

**Comment by marijnbransen1998** [comment]
closed the issue since it was resolved in #40
