### ISSUE TITLE
Writing code to check for linearity

### ISSUE THREAD

**Issue by DianneBurgess** [course-dprep/covid19_on_length_of_stay-team1#28]

**Comment by DianneBurgess** [comment]
Writing code in the [analyze.R](https://github.com/course-dprep/covid19_on_length_of_stay-team1-/blob/f3187bae935053a74112928bf117df80dd7d94d9/src/analysis/analyze.R) file to check for linearity.

**Comment by marijnbransen1998** [comment]
closed the issue since it was resolved in #40
