### ISSUE TITLE
suggested improvements to your code

### ISSUE THREAD

**Issue by hannesdatta** [course-dprep/covid19_on_length_of_stay-team1#31]
- [x] change repos URL (do not end on a dash)
- [x] #36
- [ ] #32
- [x] remove legacy files
- [x] put final report in the root directory (although, technically, it's a generated file) -- you can commit the final version of your report as well so people will see it when visiting your repository
- [ ] #33
- [ ] #34
- [ ] #35
- [x] add stuff you never want to commit to `.gitignore`

Newly added (so they can easily be converted to issues):
- [ ] #37
- [ ] #38
- [ ] #39
- [ ] #40

**Comment by KleinJonasUVT** [comment]
As addition to this list:
- [ ] Writing method and results
- [ ] Insert clean command in makefile
- [ ] pdf file for final results (or Quarto?) to present method and results

This list and the initial list need to be divided as issues over all team members.
